### PR TITLE
Fix various typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -S ./scripts/spelling.txt`

### CODE REVIEW

**Comment by arnopo** [comment]
Hello @luzpaz 
Nice tool!  Please, could you fix your commit message by adding your signed-off?

Could you also tell me if it is possible to use the tool in a github action on a pool request? The idea would be to integrate your tool to check codespell on a PR.

**Comment by luzpaz** [comment]
@arnopo Done!

See https://github.com/codespell-project/actions-codespell

**Review by arnopo — APPROVED** [review]
Still an issue with gitlint as autor is <luzpaz@users.noreply.github.com>)
git commit --amend --author="<luzpaz@users.noreply.github.com>)" should fix this.

**Comment by arnopo** [comment]
> See https://github.com/codespell-project/actions-codespell
Thanks !
i will have a look to it

**Comment by luzpaz** [comment]
> Still an issue with gitlint as autor is [luzpaz@users.noreply.github.com](mailto:luzpaz@users.noreply.github.com)) git commit --amend --author="[luzpaz@users.noreply.github.com](mailto:luzpaz@users.noreply.github.com))" should fix this.

```
$ git commit --amend --author="luzpaz@users.noreply.github.com)"
fatal: --author 'luzpaz@users.noreply.github.com)' is not 'Name <email>' and matches no existing author
```

@arnopo no joy :disappointed:

**Comment by edmooring** [comment]
> > Still an issue with gitlint as autor is [luzpaz@users.noreply.github.com](mailto:luzpaz@users.noreply.github.com)) git commit --amend --author="[luzpaz@users.noreply.github.com](mailto:luzpaz@users.noreply.github.com))" should fix this.
> 
> ```
> $ git commit --amend --author="luzpaz@users.noreply.github.com)"
> fatal: --author 'luzpaz@users.noreply.github.com)' is not 'Name <email>' and matches no existing author
> ```
> 
> @arnopo no joy 😞

It looks like gitlint wants a "real" email address, you might try
`git commit --amend --author="Luz Paz" <luzpaz@users.noreply.github.com>"`
although it looks like gitlint also might not like anybody @users.noreply.github.com.

**Review by edmooring — APPROVED** [review]
I can live with the commit message now:)
The typo corrections are very welcome.

**Pull request merged**
