### PR TITLE
zephyr: cache: Use new cache API

### PR DESCRIPTION
**Pull request by carlocaione**
Use the new cache API for the cache hooks.

Signed-off-by: Carlo Caione <ccaione@baylibre.com>

### CODE REVIEW

**Review by arnopo — APPROVED** [review]

**Comment by carlocaione** [comment]
DNM. This is a draft.

**Comment by carlocaione** [comment]
https://github.com/zephyrproject-rtos/zephyr/pull/50988 is now ready for merging so it's time to push this.

**Review by carlescufi — APPROVED** [review]

**Review by edmooring — APPROVED** [review]
Looks ready to go as soon as the API changes are merged into Zephyr.

**Comment by carlescufi** [comment]
Not sure what order do you want to merge this in @carlocaione and @edmooring. Zephyr has a [fork of libmetal](https://github.com/zephyrproject-rtos/libmetal) so we either push the change there first and then merge the [Zephyr PR](https://github.com/zephyrproject-rtos/zephyr/pull/50988) or we merge here, we update the fork with this upstream, and then merge the Zephyr PR.

**Comment by arnopo** [comment]
Notice that the Forks on Zephyr has to be updated based on the last release (quite overloaded, so I do not find time to do it yet)

In the past When we needed a patch on zephyr OpenAMP modules between releases, we first integrated the patch in OpenAMP and then rebased the Zephyr fork to point to the PR sha1.

As @carlocaione gave his Go I merge it

**Pull request merged**
