### PR TITLE
CI: Use 'main' branch instead of 'master'.

### PR DESCRIPTION
**Pull request by edmooring**
See #183 for the underlying issue. 

Signed-off-by: Ed Mooring <ed.mooring@gmail.com>

### CODE REVIEW

**Review by arnopo — APPROVED** [review]
I Tested on my own github:
- create the main branch
- integrate you PR and switch the default branch to main branch
- create a  pull request to verify the CI 

Everything is working fine
I created a "main" branch. Could you rebase your PR on it before you merge it? this should avoid to break the CI until you switch the default branch to the main branch

Thanks

**Comment by edmooring** [comment]
I'm not sure why you created the "main" branch. GitHub provides a lot of support for renaming the default branch, including redirection of pull requests. I have tested the process on my local open-amp repo.

1. I created a pull request and verified that CI and compliance ran against it.
2. Renamed "master" to "main". 
3. Force pushed to my pull request branch. CI and compliance were not run.
4. Updated the configuration files in .github/workflows and pushed to main.
5. Force pushed to my pull request branch again. CI and compliance run.

So it looks like the only problem with CI is the window between steps 2 and 4. If we do those two steps close together, I don't think we'll run into any trouble. This would let us take advantage of the GitHub support for this, including providing people with instructions on how to bring their local repositories in sync with us after the rename.

I think we should delete the current "main" branch and rename the "master branch" just before merging the configuration file changes.

**Comment by arnopo** [comment]
> I'm not sure why you created the "main" branch. GitHub provides a lot of support for renaming the default branch, including redirection of pull requests. I have tested the process on my local open-amp repo.
> 
> 1. I created a pull request and verified that CI and compliance ran against it.
> 2. Renamed "master" to "main".
> 3. Force pushed to my pull request branch. CI and compliance were not run.
> 4. Updated the configuration files in .github/workflows and pushed to main.
> 5. Force pushed to my pull request branch again. CI and compliance run.
> 
> So it looks like the only problem with CI is the window between steps 2 and 4. If we do those two steps close together, I don't think we'll run into any trouble. This would let us take advantage of the GitHub support for this, including providing people with instructions on how to bring their local repositories in sync with us after the rename.
> 
> I think we should delete the current "main" branch and rename the "master branch" just before merging the configuration file changes.

No worries, If you prefer this way, that ok for me. do you make it or do you want that i merge the PR and change the branch name?

**Comment by edmooring** [comment]
@arnopo, I will take care of it.

**Pull request merged**
